### PR TITLE
Fiexd extend ILayer interface and add addTo function.

### PR DESCRIPTION
**Pull request by wandergis**

### CODE REVIEW

**Comment by bbecquet** [comment]
Hi, and thanks for your contribution.

Can you explain why you decided to extend directly from `Class` instead of `Layer`? This forces you to implement this new `addTo` function yourself, instead of letting the base class do the job. At the end the object seems to behave like a real layer for this add behavior, but isn't a real one, so I don't see the point.

BTW, thanks as it forced me to review my current implementation, and I found it's buggy 'cause `onAdd` & `onRemove` don't return `this` as they should [according to the doc](http://leafletjs.com/reference-1.0.0.html#layer-onadd).

**Comment by wandergis** [comment]
That's because  i use leaflet@0.7.7 not with 1.0.0,so i just change it extend from `Layer` to `Class`,and add `addTo` function to it .

**Comment by wandergis** [comment]
I'm sorry that i didn't read the readme.md seriously. 😢

**Comment by bbecquet** [comment]
I'm sorry too, I should have made things clearer about versions, and also understood this was the problem. It's been too long since I've touched the 0.7 version!
Hope everything works for you now :)

**Pull request closed without merging**
